from PyQt5 import QtCore, QtWidgets, QtGui
from PyQt5.QtCore import Qt
from PyQt5.QtGui import *
from PyQt5.QtWidgets import QMainWindow, QLabel

class Ui_PreviewWindow(QMainWindow):
    """Class representing the preview window used to rerder images and to see how the
    chooser window is going to look like"""
    def __init__(self, mainWin):
        """Initializes the class"""
        super().__init__()
        self.imageLabels = []   # a list of labels with images
        self.firstIndex = 0   # index of the first clicked image
        self.secondIndex = 0    # index of the second clicked image
        self.mainWin = mainWin    # main window object
        self.i = 0    # i index of the grid
        self.j = 0    # j index of the grid
        self.selected = []    # list of selected image names
        self.rows = 0   # number of rows of the gallery grid
        self.cols = 0   # number of columns of the gallery grid
        self.highlighted = []   # list of clicked images, max length is 2
        self.setupUi(self)

    def setupUi(self, MainWindow):
        """Sets up UI"""
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(651, 498)   # sets the windows size, values were generated by UI generator
        MainWindow.setWindowIcon(QtGui.QIcon("icon.png"))   # sets the windows icon

        self.centralwidget = QtWidgets.QWidget(MainWindow)    # creates the main widget
        self.centralwidget.setObjectName("centralwidget")

        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)   # creates the grid layout for the whole window
        self.gridLayout.setObjectName("gridLayout")
        # done button that saves the changes and closes the window
        self.doneButton = QtWidgets.QPushButton(self.centralwidget)
        self.doneButton.setObjectName("pushButton_3")
        self.doneButton.clicked.connect(lambda: self.done())
        self.gridLayout.addWidget(self.doneButton, 1, 2, 1, 1)
        # close button that closes the window
        self.closeButton = QtWidgets.QPushButton(self.centralwidget)
        self.closeButton.setObjectName("pushButton")
        self.closeButton.clicked.connect(self.close)
        self.gridLayout.addWidget(self.closeButton, 1, 3, 1, 1)
        # spacer item for placing the buttons
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 1, 4, 1, 1)
        # a widget that holds image
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        # grid layout for the widget with images
        self.gallerygrid = QtWidgets.QGridLayout(self.frame)
        self.gallerygrid.setObjectName("gridLayout_2")
        self.gallerygrid.setSpacing(20)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 6)
        # switch button that switches two highlighted pictures
        self.switchButton = QtWidgets.QPushButton(self.centralwidget)
        self.switchButton.setObjectName("pushButton_2")
        self.switchButton.clicked.connect(self.switch)
        self.gridLayout.addWidget(self.switchButton, 1, 5, 1, 1)
        # spacer item for placing the buttons
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem1, 1, 1, 1, 1)

        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        """Sets text on window content"""
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Preview"))
        self.doneButton.setText(_translate("MainWindow", "Done"))
        self.closeButton.setText(_translate("MainWindow", "Close"))
        self.switchButton.setText(_translate("MainWindow", "Switch"))
        
    def done(self):
        """Runs after done button is pressed"""
        self.mainWin.updateSelected(self.selected)    # sets reordered image names to main window
        self.mainWin.show()
        self.close()

    def highlight(self, event, label):
        """Highlights clicked image, only 2 images can be highlighted at the same time,
        if 2 are highlighted and use clicks on 3rd one, the 1st one get unhighlighted and the 3rd one
        gets highligted, the 2nd one is then 1st one (queue)"""
        if len(self.highlighted) == 0:
            label.setStyleSheet("border: 5px inset red")
            self.highlighted.append(label)
        elif len(self.highlighted) == 1:
            if self.highlighted[0] == label:
                label.setStyleSheet("border: 5px inset white")
                self.highlighted.remove(label)
            else:
                label.setStyleSheet("border: 5px inset red")
                self.highlighted.append(label)
        elif len(self.highlighted) == 2:
            if self.highlighted[0] == label or self.highlighted[1] == label:
                label.setStyleSheet("border: 5px inset white")
                self.highlighted.remove(label)
            else:
                self.highlighted[0].setStyleSheet("border: 5px inset white")
                self.highlighted.pop(0)
                label.setStyleSheet("border: 5px inset red")
                self.highlighted.append(label)
        else:
            return


    def switch(self):
        """Switches 2 highlighted images and redraws the widget"""
        self.i = 0
        self.j = 0

        if len(self.highlighted) < 2:
            return
        # search for indexes of labels
        for i, lab in enumerate(self.imageLabels):
            if lab == self.highlighted[0]:
                self.firstIndex = i
            if lab == self.highlighted[1]:
                self.secondIndex = i

        for lab in self.imageLabels:
            lab.close()
        # switches them
        firstLab = self.imageLabels[self.firstIndex]
        secondLab = self.imageLabels[self.secondIndex]
        self.imageLabels[self.firstIndex] = secondLab
        self.imageLabels[self.secondIndex] = firstLab
        # switches the name list
        firstName = self.selected[self.firstIndex]
        secondName = self.selected[self.secondIndex]
        self.selected[self.firstIndex] = secondName
        self.selected[self.secondIndex] = firstName
        # unhighlight
        self.highlighted[0].setStyleSheet("border: 5px inset white")
        self.highlighted[1].setStyleSheet("border: 5px inset white")
        self.highlighted = []   # clears clicked list
        # redraw
        for lab in self.imageLabels:
            self.gallerygrid.addWidget(lab, self.i, self.j)
            lab.show()
            self.i = self.i + 1
            if self.i == self.rows:
                self.i = 0
                self.j = self.j + 1


    def organizeImages(self, filename):
        """Puts images into scroll area"""
        if filename == '':
            return
        label = QLabel(self.frame)     # label that holds the pixmap
        pixmap = QPixmap(filename)     # pixmap that hold the image
        label.setFixedSize(120, 120)
        modpixmap = pixmap.scaled(110, 110)
        label.setPixmap(modpixmap)
        label.setAlignment(Qt.AlignCenter)
        label.setStyleSheet("background-color: white")
        label.mousePressEvent = lambda event: self.highlight(event, label)
        self.imageLabels.append(label)
        self.gallerygrid.addWidget(label, self.i, self.j)

        self.i = self.i + 1
        if self.i == self.rows:
            self.i = 0
            self.j = self.j + 1

    def loadImages(self, selected, rows, cols):
        """Loads images.
        Is called from the main window"""
        self.rows = rows
        self.cols = cols
        self.selected = selected
        self.setupGrid()
        for filename in self.selected:
            self.organizeImages(filename)

    def setupGrid(self):
        """Sets up grid according to layout selected in the main window"""
        for i in range(0, self.rows):
            self.gallerygrid.setRowStretch(i, 1)

        for i in range(0, self.cols):
            self.gallerygrid.setColumnStretch(i, 1)

    def closeEvent(self, QCloseEvent):
        """Defines a close event that shows the main window and closes results window"""
        self.mainWin.show()
        self.close()